version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: mkode-db
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mkode
    volumes:
      - postgres_data_v2:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: mkode-redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

volumes:
  postgres_data_v2: {}
  redis_data: {}
